In [1]:
from chap10 import *
p = np.array([2, 1])
w = np.array([1, 1])

def directional_variance_gradient_iについて

In [2]:
projection_length = np.dot(p, direction(w))
projection_length   

2.1213203435596424

In [3]:
gradient = np.array([2 * projection_length * x_ij for x_ij in p])
gradient

array([8.48528137, 4.24264069])

`alpha=0.01`としてw方向の分散varianceを求める。

In [4]:
directional_variance_i(p, w)    #更新前


4.499999999999999

In [5]:
updated_w = w + gradient * 0.01
directional_variance_i(p, updated_w)    #更新後


4.558217724010755

値が上昇したのでwを更新

In [6]:
w = updated_w
w

array([1.08485281, 1.04242641])

繰り返していくと,wの方向が(0, 0) -> pの方向に近づいて行く

In [7]:
X = np.array([p])
guess = np.array([1. for _ in X[0]])  # 初期値, 各成分が1
unscaled_maximizer = maximize_stochastic(
    lambda x_i, _, w: directional_variance_i(x_i, w),  # 各点に対しw方向の分散を計算してその和が最大になるようにする
    lambda x_i, _, w: directional_variance_gradient_i(x_i, w),  # 各点に対しw方向の
    X,
    np.array([None for _ in X]),  # dummyのy
    guess  # 初期値
)
direction(unscaled_maximizer)

array([0.89442504, 0.4472179 ])